export const API_KEY = "1cf8999b3a4fae5d3823303ca75a3c03";

export const movieMenu = [
  { id: 1, name: "Upcoming Movies", route: "/upcoming" },
  { id: 2, name: "Trending Movies", route: "/trending" },
];

export const FETCH_MOVIE_REQUEST = "FETCH_MOVIE_REQUEST";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";
export const SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST";

export const IMAGE_PATH = "http://image.tmdb.org/t/p/w500";
export const API_ENDPOINT = "https://api.themoviedb.org/3/";

export const peopleRoute = "/people";
export const tvShowRoute = "/tvShows";

export const FETCH_PEOPLE_REQUEST = "FETCH_PEOPLE_REQUEST";
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
export const FETCH_PEOPLE_FAILURE = "FETCH_PEOPLE_FAILURE";
export const SEARCH_PEOPLE_REQUEST = "SEARCH_PEOPLE_REQUEST";

export const FETCH_TRENDING_REQUEST = "FETCH_TRENDING_REQUEST";
export const FETCH_TRENDING_SUCCESS = "FETCH_TRENDING_SUCCESS";
export const FETCH_TRENDING_FAILURE = "FETCH_TRENDING_FAILURE";
export const SEARCH_TRENDINGMOVIE_REQUEST = "SEARCH_TRENDINGMOVIE_REQUEST";

export const FETCH_UPCOMINGMOVIES_REQUEST = "FETCH_UPCOMINGMOVIES_REQUEST";
export const FETCH_UPCOMINGMOVIES_SUCCESS = "FETCH_UPCOMINGMOVIES_SUCCESS";
export const FETCH_UPCOMINGMOVIES_FAILURE = "FETCH_UPCOMINGMOVIES_FAILURE";
export const SEARCH_UPCOMING_REQUEST = "SEARCH_UPCOMING_REQUEST";

export const FETCH_DETAILVIEW_REQUEST = "FETCH_DETAILVIEW_REQUEST";
export const FETCH_DETAILVIEW_SUCCESS = "FETCH_DETAILVIEW_SUCCESS";
export const FETCH_DETAILVIEW_FAILURE = "FETCH_DETAILVIEW_FAILURE";

export const FETCH_TVSHOW_REQUEST = "FETCH_TVSHOW_REQUEST";
export const FETCH_TVSHOW_SUCCESS = "FETCH_TVSHOW_SUCCESS";
export const FETCH_TVSHOW_FAILURE = "FETCH_TVSHOW_FAILURE";
export const SEARCH_TV_REQUEST = "SEARCH_TV_REQUEST";

export const FETCH_REVIEWS_SUCCESS = "FETCH_REVIEWS_SUCCESS";
